package constanta

const SecretKey = "Very Secret"
const StatusTemporaryRedirect = "Temporary Redirect"
const StatusUnauthorized = "Unauthorized"
const UserNotFound = "User Not Found"
const DataScopeNotFound = "DataScope Not Found"
const ClientNotFound = "Client Not Found"
const DataContextNotFound = "Data Context Not Found"
const UserRoleNotFound = "UserRole Not Found"
const WrongPassword = "Wrong Password"
const WrongClientSecret = "Wrong Client Secret"
const AuthorizeCodeNotExist = "Authorize Code Not Exist"
const InvalidToken = "Invalid Token"
const CannotConvertToCtxContext = "Cannot Convert To CtxContext"
const RoleBuyer = "buyer"
const RoleDistributor = "distributor"
const RolePrincipal = "principal"
const RoleAdmin = "admin"
const State = "state"
const ExpiredToken = "Expired Token"
const SomeoneAlreadyUseThisEmail = "Someone Already Use This Email"
const InvalidOtp = "Invalid OTP"
const SubjectUserCreate = "Your OTP from Simple Oauth Service"

//HTTP STATUS
//Successful responses
const Status200 = "OK"
const Status201 = "Created"
const Status202 = "Accepted"
const Status203 = "Non-Authoritative Information"
const Status204 = "No Content"
const Status205 = "Reset Content"
const Status206 = "Partial Content"

//Redirection messages
const Status300 = "Multiple Choices"
const Status301 = "Moved Permanently"
const Status302 = "Found"
const Status303 = "See Other"
const Status304 = "Not Modified"
const Status305 = "Use Proxy"
const Status306 = "unused"
const Status307 = "Temporary Redirect"
const Status308 = "Permanent Redirect"

//Client error responses
const Status400 = "Bad Request"
const Status401 = "Unauthorized"
const Status402 = "Payment Required"
const Status403 = "Forbidden"
const Status404 = "Not Found"
const Status405 = "Method Not Allowed"
const Status406 = "Not Acceptable"
const Status407 = "Proxy Authentication Required"
const Status408 = "Request Timeout"
const Status409 = "Conflict"
const Status410 = "Gone"
const Status411 = "Length Required"
const Status412 = "Precondition Failed"
const Status413 = "Payload Too Large"
const Status414 = "URI Too Long"
const Status415 = "Unsupported Media Type"
const Status416 = "Range Not Satisfiable"
const Status417 = "Expectation Failed"
const Status418 = "I'm a teapot"
const Status422 = "Unprocessable Entity"
const Status425 = "Too Early"
const Status426 = "Upgrade Required"
const Status428 = "Precondition Required"
const Status429 = "Too Many Requests"
const Status431 = "Request Header Fields Too Large"
const Status451 = "Unavailable For Legal Reasons"

//Server error responses
const Status500 = "Internal Server Error"
const Status501 = "Not Implemented"
const Status502 = "Bad Gateway"
const Status503 = "Service Unavailable"
const Status504 = "Gateway Timeout"
const Status505 = "HTTP Version Not Supported"
const Status506 = "Variant Also Negotiates"
const Status507 = "Insufficient Storage"
const Status508 = "Loop Detected"
const Status510 = "Not Extended"
const Status511 = "Network Authentication Required"
